#!/usr/bin/env bash

set -euo pipefail

# Configuration
REPO_URL="https://github.com/ArtashesSoghomonyan/todo-list-cli"
INSTALL_DIR="${HOME}/.local/share/todo-list-cli"
BIN_DIR="${HOME}/.local/bin"
COMMAND_NAME="todo"
PYTHON_MIN_MAJOR=3
PYTHON_MIN_MINOR=12

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No color

info() {
    echo -e "${BLUE}[info] $* ${NC}"
}

success() {
    echo -e "${GREEN}[ok] $* ${NC}"
}

warn() {
    echo -e "${YELLOW}[warn] $* ${NC}"
}

error() {
    echo -e "${RED}[error] $* ${NC}" >&2; exit 1
}

# Python check
find_python() {
    local python_cmd=""

    for cmd in python3 python; do
        if command -v "$cmd" &>/dev/null; then
            local ver
            ver=$("$cmd" -c "import sys; print(f'{sys.version_info.major} {sys.version_info.minor}')" 2>/dev/null) || continue
            local major minor
            major=$(echo "$ver" | cut -d' ' -f1)
            minor=$(echo "$ver" | cut -d' ' -f2)
            if [ "$major" -ge "$PYTHON_MIN_MAJOR" ] && [ "$minor" -ge "$PYTHON_MIN_MINOR" ]; then
                python_cmd="$cmd"
                break
            fi
        fi
    done

    if [ -z "$python_cmd" ]; then
        error "Python ${PYTHON_MIN_MAJOR}.${PYTHON_MIN_MINOR}+ is required but was not found on your system.
       Please install Python from https://www.python.org/downloads/ and try again."
    fi

    echo "$python_cmd"
}

# Download source
download_source() {
    if [ -d "$INSTALL_DIR" ]; then
        warn "Existing installation found at ${INSTALL_DIR}."

        if command -v git &>/dev/null && [ -d "${INSTALL_DIR}/.git" ]; then
            info "Updating via git..."
            git -C "$INSTALL_DIR" pull --quiet
            success "Repository updated."
            return
        else
            info "Removing old installation before reinstalling..."
            rm -rf "$INSTALL_DIR"
        fi
    fi

    mkdir -p "$INSTALL_DIR"

    if command -v git &>/dev/null; then
        info "Cloning repository..."
        git clone --quiet --depth=1 "$REPO_URL" "$INSTALL_DIR"
        success "Repository cloned."
    else
        info "git not found — downloading archive instead..."
        local archive_url="${REPO_URL}/archive/refs/heads/main.tar.gz"

        if command -v curl &>/dev/null; then
            curl -sSL "$archive_url" | tar -xz --strip-components=1 -C "$INSTALL_DIR"
        elif command -v wget &>/dev/null; then
            wget -qO- "$archive_url" | tar -xz --strip-components=1 -C "$INSTALL_DIR"
        else
            error "Neither curl, wget, nor git is available. Cannot download the source."
        fi

        success "Archive downloaded and extracted."
    fi
}

# Virtual environment & dependencies
setup_venv() {
    local python_cmd="$1"
    local venv_dir="${INSTALL_DIR}/.venv"

    info "Creating virtual environment..."
    "$python_cmd" -m venv "$venv_dir"

    info "Upgrading pip..."
    "${venv_dir}/bin/pip" install --quiet --upgrade pip

    info "Installing dependencies..."
    "${venv_dir}/bin/pip" install --quiet rich

    success "Virtual environment ready."
}

# Launcher script
create_launcher() {
    mkdir -p "$BIN_DIR"

    cat > "${BIN_DIR}/${COMMAND_NAME}" <<EOF
#!/usr/bin/env bash
# Launcher for todo-list-cli — generated by install.sh
PYTHONPATH="${INSTALL_DIR}" exec "${INSTALL_DIR}/.venv/bin/python" "${INSTALL_DIR}/main.py" "\$@"
EOF

    chmod +x "${BIN_DIR}/${COMMAND_NAME}"
    success "Launcher created at ${BIN_DIR}/${COMMAND_NAME}."
}

# PATH setup
configure_path() {
    # Already on PATH — nothing to do
    if [[ ":${PATH}:" == *":${BIN_DIR}:"* ]]; then
        success "${BIN_DIR} is already in your PATH."
        return
    fi

    # Pick the right shell rc file
    local shell_rc=""
    case "${SHELL:-}" in
        */zsh)  shell_rc="${HOME}/.zshrc" ;;
        */bash) shell_rc="${HOME}/.bashrc" ;;
        */fish) shell_rc="${HOME}/.config/fish/config.fish" ;;
        *)      shell_rc="${HOME}/.profile" ;;
    esac

    local path_snippet='export PATH="$HOME/.local/bin:$PATH"'

    # fish uses a different syntax
    if [[ "${SHELL:-}" == */fish ]]; then
        path_snippet="fish_add_path \$HOME/.local/bin"
    fi

    if [ -f "$shell_rc" ] && grep -qF ".local/bin" "$shell_rc"; then
        success "PATH entry already exists in ${shell_rc}."
    else
        {
            echo ""
            echo "# Added by todo-list-cli installer"
            echo "$path_snippet"
        } >> "$shell_rc"
        warn "Added ${BIN_DIR} to PATH in ${shell_rc}."
        warn "Run 'source ${shell_rc}' or open a new terminal for the change to take effect."
    fi
}

# Main
main() {
    echo ""
    echo -e "${BOLD} Installing todo-list-cli ${NC}"
    echo ""

    local python_cmd
    python_cmd=$(find_python)
    success "Python found: $(command -v "$python_cmd") ($("$python_cmd" --version))"

    download_source
    setup_venv "$python_cmd"
    create_launcher
    configure_path

    echo ""
    echo -e "${GREEN}${BOLD}  All done! todo-list-cli is installed.${NC}"
    echo ""
    echo "  Getting started:"
    echo "    ${COMMAND_NAME} --help"
    echo "    ${COMMAND_NAME} --add \"Buy groceries\""
    echo "    ${COMMAND_NAME} --list"
    echo "    ${COMMAND_NAME} --check 1"
    echo "    ${COMMAND_NAME} --remove 1"
    echo ""
    echo    "  To uninstall:"
    echo    "    curl -sSL ${REPO_URL}/raw/main/scripts/uninstall.sh | bash"
    echo ""
}

main "$@"
